const sampleQuotes = [
  "The quick brown fox jumps over the lazy dog. This sentence uses every letter of the alphabet.",
  "Typing tests are a fun way to improve your speed. They also help track your progress over time.",
  "Practice makes perfect. Repetition builds confidence and skill.",
  "Speed and accuracy are both important. One without the other can lead to poor habits.",
  "Consistency is the key to progress. Small efforts each day compound into big results.",
  "Focus on accuracy before speed. It’s easier to build speed once precision is mastered.",
  "Typing is a skill that improves with repetition. Daily practice sharpens your reflexes.",
  "The best way to learn is by doing. Start typing now and improve with each word.",
  "Short sentences build typing rhythm. They are easier to digest and master.",
  "Fast fingers require sharp minds. Stay alert and focused to increase speed.",
  "Errors slow you down more than you think. Correcting them takes extra time and energy.",
  "Correcting mistakes takes time. Avoid them by typing slowly and carefully.",
  "Never sacrifice accuracy for speed. Rushing leads to more errors.",
  "Good posture leads to better typing. Sit upright with both feet flat on the floor.",
  "Your hands remember what you teach them. Train them with proper finger placement.",
  "Type like you think, clearly and quickly. Don’t overthink every keystroke.",
  "Confidence comes with muscle memory. Keep typing until it feels automatic.",
  "Avoid looking at the keyboard. It slows you down and breaks concentration.",
  "Trust your muscle memory. Your fingers know where to go with practice.",
  "Challenge yourself with longer sentences. They build endurance and fluency.",
  "Use all ten fingers to maximize efficiency. Each digit has a role to play.",
  "Every word you type is progress. Even the mistakes teach you something.",
  "Backspace is not your best friend. Learn to type correctly the first time.",
  "Stay calm while typing under pressure. Stress reduces accuracy and speed.",
  "Develop a steady typing rhythm. Avoid bursts of speed followed by hesitation.",
  "Speed follows precision. Once you're accurate, your pace will increase naturally.",
  "Small improvements lead to great gains. Don’t underestimate incremental progress.",
  "Typing is the modern writer’s sword. Master it to express ideas swiftly.",
  "Clear thoughts lead to faster typing. Know what you want to say before you begin.",
  "Speed is a byproduct of consistency. Keep practicing and it will come.",
  "Typing without errors is an art. Aim for both speed and elegance.",
  "Improvement comes from smart practice. Don’t just type — type with purpose.",
  "Don't rush. Type with intent. Every keystroke matters.",
  "Type like you're telling a story. Let your thoughts flow into the keys.",
  "Keep your eyes on the screen. It helps maintain flow and awareness.",
  "Let your thoughts guide your fingers. Trust your instincts and keep going.",
  "Errors are opportunities to improve. Learn what caused them and adjust.",
  "Muscle memory builds over time. Repetition is the key to automation.",
  "The keyboard is your canvas. Create words with rhythm and flow.",
  "Fast typing saves hours over time. The investment in learning pays off.",
  "Focus breeds improvement. Distractions kill typing efficiency.",
  "Typing teaches focus and precision. Both are useful beyond the keyboard.",
  "Mastery comes from repetition. There are no shortcuts to excellence.",
  "Challenge yourself to be consistent. Predictability leads to progress.",
  "Typing is thinking in motion. Let your thoughts travel through your fingers.",
  "WPM is just one metric. Focus on clarity and understanding.",
  "Push yourself, but not too hard. Burnout slows your growth.",
  "Discipline shapes great typists. Practice daily, even if only briefly.",
  "Good habits lead to great results. Avoid shortcuts that create flaws.",
  "Warm up your fingers before each session. Stretch and start slow.",
  "Typing speed reflects mental flow. Clear thoughts yield fast results.",
  "Be patient with your progress. Mastery takes time.",
  "Each keystroke counts. Don’t waste them on sloppiness.",
  "Type like you talk, with intention. Make your words deliberate.",
  "Use tests to track growth, not perfection. Improvement is the goal.",
  "Sharp minds make sharp typists. Keep your brain engaged while typing.",
  "Eliminate distractions and focus. Turn off notifications during practice.",
  "Typing helps you think faster. It becomes a tool for mental clarity.",
  "Every mistake teaches something new. Review them and adapt.",
  "Slow is smooth, smooth is fast. Rushing leads to chaos.",
  "Set realistic goals for improvement. Track them and stay accountable.",
  "Build accuracy before speed. A strong foundation supports rapid growth.",
  "Routines help reinforce skills. Set a time each day to practice.",
  "Quality typing beats fast typing. Don’t rush what should be precise.",
  "Type from the heart. Let your fingers speak for your thoughts.",
  "Keyboard mastery takes time. Be patient and persistent.",
  "Repetition builds strength. Practice is your gym.",
  "Measure progress weekly, not daily. Long-term trends are what matter.",
  "Keep practicing even when it's hard. Breakthroughs follow plateaus.",
  "Use your thumbs for the spacebar. It’s the most efficient method.",
  "Keep your wrists relaxed. Tension slows your response time.",
  "Eyes forward, fingers flying. Stay focused and stay fluid.",
  "Find your flow state. Typing becomes effortless in it.",
  "Typing fast feels like flying. Let yourself enjoy the speed.",
  "Small steps forward still move you. Don't worry about being perfect.",
  "Mistakes are just part of learning. Embrace and learn from them.",
  "Stay relaxed to type faster. Tension breeds mistakes.",
  "Set goals and stick to them. Motivation keeps you moving.",
  "Good form prevents fatigue. Stay comfortable for long sessions.",
  "Use proper finger placement. It pays off with every word.",
  "Typing sharpens your focus. It improves your thinking.",
  "Stay mindful while typing. Don’t drift into autopilot.",
  "Break down complex sentences. Make them easier to process.",
  "Don't be afraid of long words. They improve your dexterity.",
  "Review your typing logs. Track your weak points.",
  "Improve one habit at a time. Don’t overwhelm yourself.",
  "Stay consistent, even when slow. Speed will follow.",
  "Find your natural rhythm. Don’t force what doesn’t feel right.",
  "Speed follows understanding. Know what you type.",
  "Avoid bad habits early. They’re hard to break later.",
  "Type what you think, not what you see. Stay one step ahead.",
  "Relearn if needed — it's worth it. Quality beats speed.",
  "Typing reveals your thought patterns. Pay attention to your flow.",
  "Stay curious about your progress. Look for patterns and trends.",
  "Typing is a lifelong skill. It pays dividends forever.",
  "You get faster when you stop trying to be fast. Let flow guide you.",
  "Typing helps organize your thoughts. It brings clarity to chaos.",
  "Better typing leads to better productivity. You work faster and think clearer.",
  "Every sentence is a step forward. Don’t underestimate small wins.",
  "Keep your focus on one line at a time. Don’t let the rest distract you.",
  "Typing well is a superpower. Use it to your advantage.",
  "Fast typing is a competitive advantage. Invest in it.",
  "Precision gives you confidence. Accuracy makes everything easier.",
];

export default sampleQuotes;
